apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-credentials
  namespace: loki
spec:
  encryptedData:
    admin-password: AgALnCr2/FOSgOZyd/sAuI9zMbP1QgFNPebhQi1SDdo5/BcfraUTpb+qb2Pvl2Mh3QmLe1NUYjyM9PUFlTVowEqI2/bzrp2D5sdXUBSr0+tBu180SeZ3UVnNx/KmJ3MsVoFAdTBwZH3AqWV1SPeJ8avgNqGVW3paJrttcNY6QVqqLQ8isyiS30hYAfy288qjR5edBlGuwqlzcqnqVUUqSUS+rudtYlU5Yj/0oyzTr/+rtlDgxycjU8qWmg9+A5Z188vY3SSz7qwDXNpyhXZo/DRX1eHJtPSuOfuI/fHsXKy8Bty5UEmcLcfUcM0w2SB+3LOrNA/B1I8jDAOMlrMAr80Qi8GCx2TS7m7ggF2SvtGQl8lZIpYvk1Uvo5Vw++suM2jkD35/n9jQxz3d0P767NEWp8/gNZSaGv5eRFinsyIMVCDqHkytIdiaIwDxo/SQ+uVngnzpwjFCnfcCME2KdErVv9bvEHozDZPWFKrj9bVYAtzEDCmgmJPGt1bsH0bGNZ/pOuLldMYabYW0UzjJo95MrIL01qtvfvYM8hIceCHqQEhUU6Eepaw/8ZuNPcvKndfzVPI7NjdtvoMYNryBYV8j2kN+mcMqxFr3CH8zDlXcB9UBAKq/M12e7nyeeSe3CPEGjEO+JebbDPkpbw5UWZDOduxhUfrFFm2NnGqVRjYFNOsY7D2QF8FkCj+kI35lfzZNIWKTJxa1bAITRpftApKIf9IomUM9MRBxCApvwdS7E94rDwcN2G9AZbIJ
    admin-user: AgCG3Y9qrn1Ru1icWIZA6DfiQBFDyj5XfOXAzZaMnCOlvanpUJbZGPfvd75heY//pessWVzGfBziDBk3TsQoK2hiByNrFL+O6qAv+aGzJiTLXGqS7PrZCRY70Z/ioMWOVlJlSxm/gjJ1mAK1oygOjFTxCCzZQXOzB4hG0QWqIPCLWU9bw+5wVNnH2DRs+sbn+fQXo21ZV9YLxEYhcI16++YStrmayKW+Epl+AGgMWps7q6eKTaNuEy26J39drbYEH2/Llf8r0gcnA04vc+NRmOwLBP0IW5wtWsixLiodVHjinzoBAox9aax5d4EmTrKHczj2u3NN3DCKUHA0yUcoDjjHgnwpFTQtlAWnEXxs59U33fW/45SWsuRZA2DGyqL6X903aYXTqswbA1Xiu+6BnyF+yGPKkmR0+hYBIwW4ZunMx3YMNdl8aprSla5VtmwNlgo8oE+nvGQ1Q8e5yr4zsNWa85UFbCZuFQr8rUAmy2kEA5aG5FfFQC3/3U635UKvPtxcHg8BSomAImTNTOiqsDHdGZnUx0VfaJtm+HpE73CPDz5+KjiL9IdIkpw1flBdbDsvBXZ5Bgn6EIs90cwB0x99QViypCYdAa1a+AEn9Stpov5YarMOnh34d5k9xHKKNANFcvJp+XtS+2n8tRDE/tseRrPGIFRDdgGbgLN0Nexdg30SgqSKeJPbQgA4N+DxLUCa4JC1kA==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-credentials
      namespace: loki
status: {}

