apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-grafana
  namespace: argocd
spec:
  destination:
    namespace: loki
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://kubernetes-charts.storage.googleapis.com
    chart: grafana
    targetRevision: 5.*
    helm:
      values: |
        ingress:
          enabled: true
          hosts:
          - loki.srueg.ch
          tls:
          - hosts:
            - loki.srueg.ch
        rbac:
          pspEnabled: false
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
            - name: Loki
              type: loki
              url: http://loki:3100
              access: proxy
              isDefault: true
        admin:
          existingSecret: grafana-credentials
