---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: loki
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:*
spec:
  releaseName: grafana
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: grafana
    version: 3.3.6
  values:
    image:
      repository: grafana/grafana
      tag: 6.2.0
    ingress:
      enabled: true
      hosts:
      - loki.srueg.ch
      tls:
      - hosts:
        - loki.srueg.ch
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          url: http://loki:3100
          access: proxy
          isDefault: true
    admin:
      existingSecret: grafana-credentials
