apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nzbget-config
  namespace: plex
  labels:
    app.kubernetes.io/name: nzbget
    app.kubernetes.io/instance: nzbget
spec:
  storageClassName: "zfs"
  resources:
    requests:
      storage: "1Gi"
  accessModes:
    - "ReadWriteOnce"
  selector:
    matchLabels:
      usage: nzbget-config
