apiVersion: v1
kind: Service
metadata:
  name: nzbget
  namespace: plex
  labels:
    app.kubernetes.io/name: nzbget
    app.kubernetes.io/instance: nzbget
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: nzbget
      port: 6789
      targetPort: nzbget
  selector:
    app.kubernetes.io/name: nzbget
    app.kubernetes.io/instance: nzbget
