---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: vivanina-demo
spec:
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: postgresql
    version: 8.1.4
  values:
    postgresqlDatabase: vivanina-demo
    existingSecret: vivanina
    persistence:
      existingClaim: postgresql
