apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: plex-claim
  namespace: plex
spec:
  encryptedData:
    plex-claim: AgCSldaTDa95Z3Vh6JN3FFeM/YDbsZocphxNhwqBOfxje6TQNzhyd25vC/v6DnKN/xxx4mvhjzZG+0dHwBLOtXkk41dPUKZmjcB7NBbXWTJsVIHvBdnJjCekW8/KShlZ8EIDxY6nGCgETEUzJOOvoOCwqHItNIobYjRvzdv93NO6tq1IA8FtI3O36NkpBmdq4nzS9SmcGNn6HgSrc6VDeZHhikJAt1iq+4TTJpLnsS6ReWBpEPNRa8+JbxvYe9ODy2OqLnQrlNVdjbl4dl5IrMb0NOf7m2XHclG2+EmB3sp9UEYvXxepQUiASExVTAuqFaoOqEvpJoszHYVW2FbNK+oH4vKe217S8vHMVmWEdfNqdS53FhZwKWdifYJsLdC8hPQNmc+vPYMB+jFsazw8RbYbaF1fAFkqauCMbyBb6Kvvl9L3xSA7Z06paYlqmAARsFvPHhx7N3M0wVwve8z2Mmso7OBRJ+bgOpvk2AKcgbG+auK9UL8+sdq4xzA2k6gLmwf+nuFFALJFjISfxWCIsDBsPHDU7dec74+fkBcSZTnrRBMF+UmXVp0AhfiLG41AmEOrlQ4iwesmUObDropbnndKhJOXM/axmkRM0SKWvv2994EpwCltLcNrbfxyF4soYfBjjXT631TvGtXsjkau/iE0KapmDmK5/ASs9ewwSmcNKBJ1yM5bayVEXqC0WCk1YaNgH5VvhDLjWdRL+CCnxDnxoIzcC9xaQfX/xA==
