apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: plex-claim
  namespace: plex
spec:
  encryptedData:
    plex-claim: AgAmfLhhADoLM+6IMQWcgojA5GB171dOmQ2Y+2PL/y/R437N2UQJpv4pOzKhfYw0cWy/jFe0/LdFe4MxxdZsrIBHHqw/NSrNrMRIgPuiEmAoA7HuYY8/1eMPPKxaqyiE9HUrNKdcnETpddqgq7brfvzvDHr7fcsiPrOXDr3AmRjDodcQiSt52Bm6sB0fB0ATN01CflDU19rXaEKMABCrUeNN49X9EKZZYzFsLhx3x1xPqNpJM74ek1rFTq/5AjbJHOS5agQSCpjNMHPczACdUxEBRvb2t3JCluMNPV6OyywyjFWQ8iqvfiCLLD++uH33E7fwmlE8c3HxZQQmyXhDI3E6jG8F90hH777pfDfF6pNG/GnD3LzQ4xH/h6KsGDjAEIeaPpTGKxAv2LGduVaKz+rgLoQ9i0JI/qvLpaBIc4kSq+djNG6S7TGq2ANc8E2SzkYlKdYTuhL0Akp/ZZCfNGn8uqt78jgxuhQaTXk1Z1rd94VpLznwijTh+NfqwU+MWE5qE3pjw0Fy/U9wD2lEvt6M5KYU8/IyNMHOk8VzQEFeTuz4/wopbZpA1ew7bWOJ2gh0J8Mu0ZLfSCi4G1JMC6o1iWoMWImWaE2aPv2ohcfrg4QLgWO53fe1byFl7f0HuqN0jwa39Srfj2YtTMOh2p1JetgqUCCL0bzgA3hTPU9hfAShwM7cofpazSm0IvFpz+d/JO09akD1YrxvIKvkLznTBT4LFUL2sYrA9g==
  template:
    metadata:
      creationTimestamp: null
      name: plex-claim
      namespace: plex
status: {}

