---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: plex
  namespace: plex
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:1.*
spec:
  releaseName: plex
  chart:
    git: https://github.com/srueg/helm-charts.git
    ref: master
    path: plex
  values:
    image:
      repository: docker.io/plexinc/pms-docker
      tag: 1.19.2.2737-b69929dab
    plexClaimSecretName: plex-claim
    persistence:
      config:
        storageClass: zfs
        selector:
          matchLabels:
            usage: plex-config
      data:
        storageClass: zfs
        selector:
          matchLabels:
            usage: plex-data
    ingress:
      enabled: true
      host: plex.srueg.ch
