apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: plex-claim
  namespace: plex
spec:
  encryptedData:
    plex-claim: AgAOZWsputB3Z5yNo/xwolwydXLSiuihSqOw3TV9JVpDqLfgTimfkLIodpskG1GRJau49VXi2UjcZpu0zcK8t5iE9XJpTQlUPs7WPsUuuz08lhMzTopFV/umPvRIvWzdakbh5DsRtdCerKCiNVBt4HG3YrxQtWRZevrCZXLaKZv2rQ1wGc4YT3htkjMBoyk9HAU23HtoBoPj9FiNANGY6WGZn3o1UlspZQssQM+Z4uRyO4cj1eXpAPfdEpYYR8oHwKqTgKk6660vgyGUrAgfbbwNJpYRdgiNgLOGKrN4BMTGfsPEMrbvziF5iN1zSEACmeGhkfWHR7miny4QLjnfZzdMw/4L0w+lpZDob8DP0QSiyyWgyz9UTYGWy7ewGdo7ORk2k/JrU3nd2Q4IZ6QdeUI/meEjOkLgzz5s7Fo0AjhnFPwFQ0qNTgp++zkGuk5Hh5vQWkwKEt5ooJQBfRyLK3SD6b7dPniQ0YHTA+sCq+6bCLNb8LGIJw8aBG4X0BoeNK4fXo7lw/cAMOQKI8HrT2UxF34OLm4vMtaPRJxyaEQ+ByxdbJAHqbXZvq3mWeEXqxXU/j2jRVwxhs64Qa6e/VjItQNpU9muWUC0Cv+/3MicRDJQYOSdBlNkzQQbC5+zzGCNFEfp2YRJMQEfWEcwWI14RnMpvgy5f6Mz6S2vYKOrUAItNSNLFG0vdjn1De/pCZx6OoIUXedLboAgX7IwHLOtJsX6Nh05bHRZmg==
  template:
    metadata:
      creationTimestamp: null
      name: plex-claim
      namespace: plex
status: {}

