apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: plex-claim
  namespace: plex
spec:
  encryptedData:
    plex-claim: AgBsrTt76G7waqqV1r7ivn9/PDLqh1f+xoXTXtYoZ5QMKdvRZBE86BSB1EaadaSyPoeop5JR5QC5pJiLMKTh2Kpiul6KulG/qRHgvoHAqLuZRES6b2ghSIsJIzCylSqBtsesvC5DyM8w+XEIK6MUl2epVYPfl3rr6LfuDDukDIhg66KmwtFr+7zSBV7R3f/arw5vt1dzD4xrqMQwDJkZT2hX6TGncZwBojYfDoMw/mBAmaJT88VS3slGP+Y8fC4sIYYHLLj5OjiIzFF1ToL4mjy/exzkNSl6+zaBgIc5OY6W67dyYTx2kz0UEtTzXICdRkckjr3zRowQOPUF8MXTpiW6LHVJYvlqNJNHANQU1FQBhmapHmQBCzLTZxuK1sChNuPCXsvvgjdX6mVdK5V8uVpcoTHpJ4OXSZYNr6PsqNxWRc+C/3VSfPBrEuKoANohFK4jWyN1j3u/Sjy+wm8vLOXl4qeArKmI4jhQnWireh7JxeV+ZlXPTVtCQBvqKeFb0Ps0uwOjvj58eqckS/Go3kYbUwBBOs4aEIhx31ZLI8c46usNW/bF6pdH6Q9fC4q7j7EEkVkBYgQaBEvW8EbAdidLSOeLEY1Qwr4KI8NMdNQIJQdBOD8XvkogH2sh3isKQh/B3NmxdXkaZOH1wNklScw24mqpTYrnbsxcTD6zOJ8oo1NbeCgPOME5ioTdm8QNJYSGe56RU//0iXFThBaz0tZBRYMZj5F6DPGnow==
  template:
    metadata:
      creationTimestamp: null
      name: plex-claim
      namespace: plex
status: {}

