apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tautulli-config
  namespace: plex
  labels:
    app.kubernetes.io/name: tautulli
    app.kubernetes.io/instance: tautulli
spec:
  storageClassName: "zfs"
  resources:
    requests:
      storage: "1Gi"
  accessModes:
    - "ReadWriteOnce"
  selector:
    matchLabels:
      usage: tautulli-config
