apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: ingress-controller
  annotations:
    flux.weave.works/automated: "false"
    flux.weave.works/tag.chart-image: semver:*
spec:
  releaseName: nginx-ingress
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: nginx-ingress
    version: 1.29.2
  values:
    controller:
      kind: DaemonSet
      hostNetwork: true
      service:
        enabled: false
      dnsPolicy: ClusterFirstWithHostNet
      extraArgs:
        default-ssl-certificate: ingress-controller/srueg-ch-wildcard-tls
    podSecurityPolicy:
      enabled: false
