apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config
  namespace: plex
  labels:
    app.kubernetes.io/name: radarr
    app.kubernetes.io/instance: radarr
spec:
  storageClassName: "zfs"
  resources:
    requests:
      storage: "1Gi"
  accessModes:
    - "ReadWriteOnce"
  selector:
    matchLabels:
      usage: radarr-config
