apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tautulli
  namespace: argocd
spec:
  destination:
    namespace: plex
    server: https://kubernetes.default.svc
  project: default
  source:
    path: media/tautulli
    repoURL: https://github.com/srueg/gitops-redkeep.git
    targetRevision: master
