apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config
  namespace: plex
  labels:
    app.kubernetes.io/name: sonarr
    app.kubernetes.io/instance: sonarr
spec:
  storageClassName: "zfs"
  resources:
    requests:
      storage: "1Gi"
  accessModes:
    - "ReadWriteOnce"
  selector:
    matchLabels:
      usage: sonarr-config
