apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: timemachine
  namespace: timemachine
spec:
  encryptedData:
    password: AgA+6GZOowkkBAe28bStKsgjjqR3vG/0He4+q3HiKVH/wn+B7PNQjoE/HCt2IfRtZsoDurLoZMbGr2YNuCT8QkbvikJ8Ic72T78620Dq2tznfKiYNEwYZ2oFUjrmn/xaMsuSW8KZ2R+6RlKEbEDUGkfn+wQuOZm4vvCeT+ETdsXy8C837kpPoOuXphBJR7KSNL70V1UjywKJkNKoCcW27KmL1g+4u0Y42tdN1284EZmQ3nuetgc+MKIGK2fS7J1/zI9RzQD1nPEA7Bbi7B7hpckuV+3ZAKcyBKGDprGLv0kJOQTtXkYIoZdWOck7Q2cQAUQq0sYsSn4fvLdKPPkiI88MfcVCu6kqpbdeO3M/8sFFWTqQqui39QTHCmyQARn2Qrzm6mjHyfkGVyJsZZ8t0j6To24sBTjkHojyxA0o6CZN4nkhUnPCDAjw86RUclUTWhMOXgt/j1/a85T2JBJWGgmnlXnjOmvSQOrFlx1rK4xfqU95PA75YaO0tdLu1fd2m1taekXlyBah7ff+oT9nTe0vy+eW0DzMm8zs4ovq0ugAcAshquj59WSDIsYpOf1fGdRJbECFZRgJ1yh8s6oRb8dUAEMCkq44gzh9Xz9ULPVlDQIpQvGIe1TwzcVytyIIBn0sOkHfaBeHRSqva8IvIbK3l6mst/p3l2xKYSzmk8JpIN/+CBFLD9N1vZgdjbFJPNj6atPeiXXBEPLjSz3WbK0JFMM=
  template:
    metadata:
      creationTimestamp: null
      name: timemachine
      namespace: timemachine
status: {}

