apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: timemachine
  namespace: timemachine
  labels:
    app.kubernetes.io/name: timemachine
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: timemachine
  replicas: 1
  serviceName: timemachine
  template:
    metadata:
      labels:
        app.kubernetes.io/name: timemachine
    spec:
      containers:
      - name: timemachine
        image: docker.io/mbentley/timemachine:smb@sha256:5086e59eaf455e981ea08522415cb075a34c588b84310d47ebffbf2bce473ec6
        env:
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: timemachine
              key: password
        ports:
        - name: smb
          containerPort: 445
          hostPort: 445
        volumeMounts:
        - name: data
          mountPath: /opt/timemachine
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: zfs
      resources:
        requests:
          storage: 1Ti
      selector:
        matchLabels:
          usage: timemachine
