---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: metrics-server
    version: 2.8.7
