apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-config
  namespace: plex
  labels:
    app.kubernetes.io/name: transmission
    app.kubernetes.io/instance: transmission
spec:
  storageClassName: "zfs"
  resources:
    requests:
      storage: "1Gi"
  accessModes:
    - "ReadWriteOnce"
  selector:
    matchLabels:
      usage: transmission-config
