apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: transmission
  namespace: plex
  labels:
    app.kubernetes.io/name: transmission
    app.kubernetes.io/instance: transmission
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: transmission
      app.kubernetes.io/instance: transmission
  serviceName: ""
  template:
    metadata:
      labels:
        app.kubernetes.io/name: transmission
        app.kubernetes.io/instance: transmission
    spec:
      containers:
        - name: transmission
          image: "docker.io/linuxserver/transmission:2.94-r3-ls51"
          imagePullPolicy: IfNotPresent
          env:
            - name: PUID
              value: "10001"
            - name: PGID
              value: "10001"
            - name: TZ
              value: "Europe/Zurich"
            - name: TRANSMISSION_WEB_HOME
              value: "/combustion-release/"
            - name: USER
              value: "transmission"
            - name: PASS
              valueFrom:
                secretKeyRef:
                  name: "transmission"
                  key: password
          volumeMounts:
            - mountPath: /config/
              name: config
              subPath: config/
            - mountPath: /watch/
              name: config
              subPath: watch/
            - mountPath: /downloads/
              name: plex
              subPath: addons/transmission/
          ports:
            - name: http
              containerPort: 9091
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          #   initialDelaySeconds: 60
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
      terminationGracePeriodSeconds: 60
      volumes:
        - name: plex
          persistentVolumeClaim:
            claimName: plex-data
        - name: config
          persistentVolumeClaim:
            claimName: transmission-config
