apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: transmission
  namespace: plex
spec:
  encryptedData:
    password: AgAN7di+8J/pwbRwytzhMc8mRbqVqeJx80uwemNGbPPakIef/5tZkVL67UnElYJzyoJt/nsnIcV61kdzmm8Nnabu4altykwfdAEt0gH2Ke8o68z7F2S5GvpBh2OLVh/qLpq72ISd4+zifoyP8Tvip5iG+0UO817geOuvH4HjUzaHcyIeK36hw1zbI9dquL2TvxWmB65koGNesUvdbyXv0wL907g1zPYvy/Xe9NBWl2DLpdORoBOpE0T7IV1IRJ8eier0Uwf4brSG4shlaQpe5ACKPYXR0+HNulNojrg77uAipPyNN2TGG04FE9SKyDXcBrosYGUH8hk48DVG6TSbrmnCg3lO11cytJoirRv5Bu6RXGiDHOiAQJCxC5ZCkcVqVkO2KHhuex76YQcZeLLhI3jsSMYIQ1snIzsw2MRyQHgKMt+Fg+JaJIPmauDRGqYLPRdWo/zfEuZCNKuaqc8vqStJ7mbKvXi9IntE7+QkQBXdSX8Ae9b3adQl5AGHpixJ5DlhI1YFL/ErnjLGXmT4Ojh90Zz/w2YiFwkdJYp8kP0DXtwmiW3v1QYqF8AMC82t+zb4G3u3R9NrRdr/1i0JpYiLKbtXF6l4VDDJ02+qPGn/DuXCzABukjZC8pTeQa0pJQsOXtxMYILUDHvnH2nrd2U2XUgJTw5YR6G0uur/op50MNWKvKKVwyjk4Q78r48mcux231sTKn1cDuSIN+uzNsR78pZs1YrZfCTXuDLHDjp1VA==
  template:
    metadata:
      creationTimestamp: null
      name: transmission
      namespace: plex
