---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openvpn-config
  namespace: openvpn
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: zfs
  selector:
    matchLabels:
      usage: openvpn-config
