---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: openvpn
  namespace: openvpn
spec:
  releaseName: openvpn
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: openvpn
    version: 3.12.3
  values:
    image:
      repository: quay.io/srueg/openvpn
      tag: latest
      pullPolicy: Always
    openvpn:
      OVPN_NETWORK: 192.168.99.0
      OVPN_SUBNET: 255.255.255.0
      OVPN_PROTO: udp
      OVPN_K8S_POD_NETWORK: 10.244.0.0
      OVPN_K8S_POD_SUBNET: 255.255.0.0
      OVPN_K8S_SVC_NETWORK: 10.96.0.0
      OVPN_K8S_SVC_SUBNET: 255.240.0.0
      dhcpOptionDomain: false
      conf: |
        push "route 192.168.0.0 255.255.0.0"
        push "dhcp-option DNS 1.1.1.1"
        max-clients 32
        client-to-client
    service:
      type: NodePort
      internalPort: 1194
      externalPort: 1194
      nodePort: 31194
    persistence:
      enabled: true
      existingClaim: openvpn-config
