---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: openvpn
  namespace: openvpn
spec:
  releaseName: openvpn
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: openvpn
    version: 3.12.3
  values:
    image:
      repository: quay.io/srueg/openvpn
      tag: latest
      pullPolicy: Always
    openvpn:
      OVPN_NETWORK: 192.168.99.0
      OVPN_SUBNET: 255.255.255.0
      OVPN_PROTO: udp
      OVPN_K8S_POD_NETWORK: nil
      OVPN_K8S_POD_SUBNET: nil
      dhcpOptionDomain: false
    service:
      type: NodePort
      internalPort: 1194
      externalPort: 1194
      nodePort: 31194
    persistence:
      enabled: true
      existingClaim: openvpn-config
