apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: oauth-proxy
  namespace: netdata
  labels:
    app: oauth-proxy
spec:
  rules:
  - host: stats.srueg.ch
    http:
      paths:
      - backend:
          serviceName: oauth-proxy
          servicePort: proxy
        path: /oauth2
  tls:
  - hosts:
    - stats.srueg.ch
