apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: oauth-config
  namespace: netdata
spec:
  encryptedData:
    client-secret: AgCRQtk66AxjY136pgy73k6vkeDA96pmH97zBM+YvKAA2Ot0uBUIo4GT6u/q75EGJFcSLdWHH3ZfBu6owA+Xcg36j2RpSa3MDvO1YQnG1F7dMppDF2gFMMZbLYJpsnTEwHwN3hZ959W/Ay/vBe/91t97TmYuN2OtHKg7JbaW9XByKgv8WPBY7cjmchi2haRaDUt//Ka4ZEAfR+lBtoSBgQs9tiyLnLBAyzrtINbbaBHLZjhRiuCyGP5Lin6EM84STFKxIOgj2Zq84/WxuUFC7zStklw98nHUsqFiW998VGV3JEmo+T58qQEAXh2xsgL3ByBmi41+K/A0zgt4r13132Gam8ZhUll50sR2YdSUz43vuqO4BxgZ2N16Q0dnGOuw1aYcRxcNVkwi1xl5751bnvao4y5f9szGj0JpoVzTHMmNnipHGWX9wR0pcsFUGvMEFHF2LIIR8+kQ45DFiJdi4ToZ2rb9w8QX8ETBsdIY5WULTwCt+JMr08rX3bJvQOm6uxgt8KCZnA5d5kr5B06uXN+3iMy2w7wI1yvDyetHrwfVjkLiiQYqXV0owsMy/Z8Sz2BYIaRVnzJnI4j8FJcqwyNs+s4R7ZGmeWF+fKoKB6dcXMrw/wsodFu4L0bJmiqGdbVrZvfAf+laD1XTslpOuXVF/Syt11Za3klcPa+sqa7/b0M1AoZojja+ZyEAM4V8PNyMOyq0KAHiQBcFxRJoJohDN6iV97MYqLf80IhesE4TSuQyaLEiyeMw
    cookie-secret: AgCRouG6gHbn7fDzac4ZNbm5NOa9/JEgjxA/7gXw/xehuOdL9sw/VzU86EWvVaMENFxwKf/CxGT92y7RWR0tdxX3R6la98LBY/Zg3wCZiSKCtDlEcrdAmcQTx2O6Z0gRgsGeKeGOncYSesigvZjWYEs9ar89BIQG+7fva4RMF+c1rrmk5zFah7gwiyc0R56AViq9HVvvHxG8wDb2J/A1jncu4zCnKCsYLtYOzyV+JazhxXA844Fu4Xicw+RNFuvJc8HuXR5grLEqBDjUd5ZE+XG7GQ7ZNrpXYJSex0YJ3JbaFjoMX+M80i3uvVqGP30XqXKvjO6B8pIGKDo18o/HOwUU3b5Z5TzrWTsZyVSS0oItXzLMgYjpp147iqS5bv5BNJWpsl3/kxP8aLwKW5vfrLIFWfxF7ZdA0tz2vrLWglXZorNebK05ydVnTlSu6QrDelPdkek00GFyyyOjOJjm6E9wU0qoB59ayHl7gB62VWlKbm3fCyLy77lNfNm6/kcWRwGR/tK5boZ44FULWbLz3wPLcwWEfAZM4z3STmU8lSFAOdvzExSEFAwH3VYFr3SpQer7xzyAdPEltQxgtcG6rH9f9YV8U4mNIxDZ2MbAZERpe0xurVdh0dvMPPQcAX8b76tM2Zwv9jYEsAVLIoK9DoczMqe3vs+WxAaqoSJobuGYUAdFixYUHOx82AJ64q/iMNRQ9U4XXnDdEjfLS4QjvhdO3mlLAoe+7TKOHHP925awvUWCJToN6p7u4fUI
  template:
    metadata:
      creationTimestamp: null
      name: oauth-config
      namespace: netdata
status: {}

