apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: oauth-config
  namespace: netdata
spec:
  encryptedData:
    client-secret: AgCAwYbSFbsJmUvNicbMhPmkjzbiuEX2EzPjiw7JnaMVQAeAyC2aTySx/vTFhU4nWmuPcm7+pw2ysu2ZB0BjByq295h5iBKkRlfYVCf/GoU/Fu4XEBtF1GJkJrjOUaL4Funi2siGxv5y7KUxnM1Gn1czUSnyqtZ3zhc5YfQQk2BHQOeF+5n4UgREpfFH/aypFeDWjpRvNHnvrXCs3WG+zLnCca/TeG6QvdwlSk0c+/+tqHMgWFwDQe+dvstg796bwVz1495a3OmSiGNaKEWOoOA+VPNrGxqNmS2QT1Q3QJm/7KFM8RVLPCgS/pirPurnRl4Okv1CHKJgI6MXxVKFREqLMfTwIHNeniyUxEMklT+qHmkCIKP/uqFX4sPSVrqDgoTppJoIW26bfeAJFbEvvqSU8jFh6tuLgtWaWdvtK+Y3wSquJBOQx4WjilyANRJ0+gNUITXoqNFA0HyhFMH5VUB6I/Wh8KOoYLdLiuOxXk0ygQZJXCkVptXBJxOPCxy7CVIhaYlUz4zdq2oiSNTtxo5Me1qKAsmRXUGAldhV8iKu5KT5UAHpiKTQhYZpkKCIvIOgv1FhH+cs2941Na6C6dwQf5dd39LcFkN8KWQO9/lGpkBf9PBE4jDGgSbZWniLW4iH5uS7IkCPFCDOhjJ4TS+8jtccgdbhjC/HuNkjHeKs8WOCSkmGUyMOVt1I49PqYMLUjEiX0FvljZic5REKkFHCm0lMSrmaEPEWIQYrftu/+cgqIxv+Xg70
    cookie-secret: AgCyIHBserotoGW1oOErrPtDkvcq7dpMMl2h3GUxvGnYuKd4CQqaeeGRbAe5xfPBCY7xQ7hbjaEG+CLjzz4Ck2zCzRhHBGYwx5Nc8JeLfv6tueehTAB+1Xc7gjdk8wrfoxcB8Pe8DCeM8bgdsFW2kRcPrhArZCW8s3CFZ7y5Z3t4o9af5Ai2SG2DlHoN3kRIjs1kuBYB1Sb3PewZZwc8lQ+9+VFC5sGhamULYFcA9fe5rby9vHhcVzP9nK7YCRYu/Gz1z2/y2EbvoS5eX+VDRBIvQKfIjf7zpsMnlllTNmaHMU0DwfeiX/pOhCDiGSqIiX+X9/F8eeGVywKUYXGhlon/83MPvM7DQ51S3kPEK3PNEsNGpPZdO9Q+PlaZptjDtLWw93sDpaTh7cpzp8RCXw1FECqPHd/fXe/bGKPgHlfA5jWtxkHLIhCEC9mtq27CFu2cNp+Z4U9DQC88GLV/SF2ypZoTm/kEri66/dAq0UtKmsvAMNONMl1DWpdgbitgEj4xC8d5wxo3S2mWNbKxOM5nHPiPsl2zpWq9WcDXOPetFJpg6X68+Itnk6Jhw24IxEd+WJs4hqoJLWz1T/730uj9qQxkMbL5LfZm5vv7SN9Z2Is51LTGWlEPOKlm3BaU4uRHCgcCLFKQLNOBHAL1aOZEh9omj9CD5l79BJvxNuLAPNG0vHy6nAHdWrYkk7vHCFQq5WOK0ahDDUKKIlGmu6N7ZLHhGwPpGIgHmJyrjmpAviHw65tUc5WvSpse
  template:
    metadata:
      creationTimestamp: null
      name: oauth-config
      namespace: netdata
status: {}

