apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: oauth-config
  namespace: netdata
spec:
  encryptedData:
    client-secret: AgBQKT3ShucXAiQAva3aqp7+Fn1+w3mWdcewq3AMx3odnE8Xe6VVrBStkijAiYlYBYaPIXMpw5ho1X8NsgsWoO7UTxpSm/ot0fUv+GeUtCW+CsT43N5EFvOTbATSVueyZf/WqrNJGUFM7uoMUU+oLOsq63oGkwgogySVUpMjlI5C9PlzRLyQ1KzhVRLBU4k1DK0y6imE9ATu9EtbNzIou9PPRzgLHgqqf9931h4wDka4PUB9Pu8jXlZhRycj8DPDw/ZzlUNYGQg5bz9bwKjpupDHKaVnQJG8bGP1Xdp9iNxhNvrQiRAQpIZvk5VDe+F1DtmmtCaBvP5hQVOAu+iP4UWY2mggaWAiFpHzOBQlL5Ws9dfDU4kxjgD4j77m4EYBWFpLXCq90VJGUiEnIXndWN4JN6XkYDqZN40uM7LY+4vCT5RCThWJQ8qxmP4cw+XBoofOPr8M74pjs5SuK3jwKyY0PqUpyCAsP+vJWD11Xo/QdohJ72TnUIFmU2TD3PzSwkz+9H7vaEJPjy8FJtOIbZQC8/4phZ06NGqv+6P8F6ZoaSjj2w7Tu6CRPb2+GJzG/t1Mw3QksAFJ0ofglZeRXLEDGQAUV4Ao8znkL3ThKLu7kDDFq+G4SW4XM7RYH2WGYYMm9NaiaUPjEi3qKK1xpYLYIQzx/C4J7UYaAYAT2VmjAoHcfXq2uUPri6xkz9DcjoWlf/6aSbVrW8nvO6CicL4crSwM0IIE8kAh7qitAPnWEJB8hBqatiiQ
    cookie-secret: AgCC+5swLH4nGbKWVjtyfQVtElRW09PrBIXd4dxruoVGPNRcZ7Gsd40+lJD/62Tac9KRAkIeuRT9yRJ5AId7iowwebuwHckzIadCipwuVGN2h51a9+plYjzbrSDp+QQRRP4Ftk0TNJP4ClEvTU9jOB3gOL60o9BQ23SjDXZaxsN+pz66wG6ztdBhADHNwQcHGrRuvKnNec0G+4z2VxhN82TMNXEkLbglMffmyh7nEknGPHBfElnQkpIXex+DRFGthR92VVVCxZe3V4U3CQojcXqn8yyXrOGeSjlNFcwfzbO6knMk8cMRyjqP+xvJvy5LWpjb7gnYfJKq6E+jp4UjsTQs8pc8mRtdTP62C3klw5qHYTUHwXNrAVN1drPE5T2nnAxdwo/XNY9B54pSAiP6SNrGGXFEQ/Kq5GWEVBvKRgvgm7rmCofctpsFzX2yX5cG122OWCkV3U8+Fxon2ZGB9IkzaWDV+it545XbahkHwdKV+/Nm5jZ5NtX00RI7Ob0+hcxe8zI47rt7SCSLuCrHvilpOYuVgaBDZ4CmJMz7lkcu+clFV4HH2u+v3pjm6LyD+W++o5yqn/szKqqplnFp4g6BLjW6CZc1uUyp/+165fMDC9IPNPAuxfG2V/q8EK2eG00YgQDC1n2LY+B5qXYPHNf4OH/Gb9DPdD5LCellYRwZr3MS/yIhkIgLYNIqsbglB8/E7G6f0WWyVc04qlEDcYYoE8bPv8/a8SAnZLTNje1eVNtG0p6NidlsBVRK
  template:
    metadata:
      creationTimestamp: null
      name: oauth-config
      namespace: netdata
status: {}

