apiVersion: v1
kind: Service
metadata:
  name: oauth-proxy
  namespace: netdata
  labels:
    app: oauth-proxy
spec:
  type: ClusterIP
  ports:
    - name: proxy
      port: 80
      targetPort: proxy
  selector:
    app: oauth-proxy
