apiVersion: v1
kind: Secret
metadata:
  name: flux-helm-repositories
  namespace: flux
type: Opaque
stringData:
  repositories.yaml: |
    apiVersion: v1
    generated: 0001-01-01T00:00:00Z
    repositories:
    - caFile: ""
      cache: /var/fluxd/helm/repository/cache/stable-index.yaml
      certFile: ""
      keyFile: ""
      name: stable
      password: ""
      url: https://kubernetes-charts.storage.googleapis.com
      username: ""
    - caFile: ""
      cache: /var/fluxd/helm/repository/cache/bitnami-index.yaml
      certFile: ""
      keyFile: ""
      name: bitnami
      password: ""
      url: https://charts.bitnami.com
      username: ""
    - caFile: ""
      cache: /var/fluxd/helm/repository/cache/loki-index.yaml
      certFile: ""
      keyFile: ""
      name: loki
      password: ""
      url: https://grafana.github.io/loki/charts
      username: ""
