---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: helm-operator
  namespace: flux
spec:
  chart:
    repository: https://charts.fluxcd.io
    name: helm-operator
    version: 0.3.0
  values:
    git:
      ssh:
        secretName: flux-git-deploy
    rbac:
      pspEnabled: true
    createCRD: false
    tillerNamespace: tiller
    configureRepositories:
      enable: true
      repositories:
      - name: stable
        url: https://kubernetes-charts.storage.googleapis.com
      - name: bitnami
        url: https://charts.bitnami.com
      - name: loki
        url: https://grafana.github.io/loki/charts
      - name: fluxcd
        url: https://charts.fluxcd.io
      - name: jetstack
        url: https://charts.jetstack.io
