apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: flux
  namespace: flux
spec:
  releaseName: flux
  chart:
    repository: https://charts.fluxcd.io
    name: flux
    version: 1.1.0
  values:
    git:
      url: git@github.com:srueg/gitops-redkeep.git
    registry:
      excludeImage: "index.docker.io/bitnami/postgresql, docker.io/netdata/netdata"
    syncGarbageCollection:
      enabled: true
      dry: false
