---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: flux
  namespace: flux
spec:
  releaseName: flux
  chart:
    repository: https://charts.fluxcd.io
    name: flux
    version: 1.0.0
  values:
    git:
      url: git@github.com:srueg/gitops-redkeep.git
    helmOperator:
      create: true
      createCRD: false
      tillerNamespace: tiller
      configureRepositories:
        enable: true
