apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: localvolume-provisioner
  namespace: localvolume-provisioner
spec:
  releaseName: localvolume-provisioner
  chart:
    git: https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner.git
    ref: v2.3.4
    path: helm/provisioner/
  values:
    common:
      namespace: localvolume-provisioner
      podSecurityPolicy: true
    classes:
      - name: zfs
        hostDir: /tank
        storageClass:
          reclaimPolicy: Retain
      - name: ssd
        hostDir: /mnt/ssd
        storageClass:
          reclaimPolicy: Retain
