---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: localvolume-provisioner
  namespace: localvolume-provisioner
spec:
  releaseName: localvolume-provisioner
  chart:
    git: https://github.com/kubernetes-incubator/external-storage.git
    ref: v5.3.0-alpha.1
    path: local-volume/helm/provisioner/
  values:
    common:
      namespace: localvolume-provisioner
    classes:
      - name: zfs
        hostDir: /tank
        storageClass:
          reclaimPolicy: Retain
