apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 2.2.11
    chart: argo-cd
    helm:
      values: |
        installCRDs: true
        dex:
          enabled: false
        server:
          extraArgs:
          - --insecure
          config:
            url: https://argocd.srueg.ch
            admin.enabled: "false"
            oidc.config: |
              name: Keycloak
              issuer: https://sso.srueg.ch/auth/realms/lab
              clientID: argocd
              clientSecret: $oidc.keycloak.clientSecret
          rbacConfig:
            policy.default: role:readonly
            policy.csv: |
              g, admin, role:admin
          ingress:
            enabled: true
            hosts: [argocd.srueg.ch]
            tls:
            - hosts:
              - argocd.srueg.ch
