apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  destination:
    namespace: sealed-secrets
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://kubernetes-charts.storage.googleapis.com/
    chart: sealed-secrets
    targetRevision: 1.*
---
apiVersion: v1
kind: Namespace
metadata:
  name: sealed-secrets
