apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vivanina-demo
  namespace: argocd
spec:
  destination:
    namespace: vivanina-demo
    server: https://kubernetes.default.svc
  project: default
  source:
    path: vivanina
    repoURL: https://github.com/srueg/gitops-redkeep.git
    targetRevision: master
    directory:
      recurse: true
