---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:v0.*
spec:
  releaseName: cert-manager
  chart:
    repository: https://charts.jetstack.io
    name: cert-manager
    version: v0.7.1
  values:
    image:
      repository: quay.io/jetstack/cert-manager-controller
      tag: v0.7.2
    securityContext:
      enabled: true
    ingressShim:
      defaultIssuerName: letsencrypt-production
      defaultIssuerKind: ClusterIssuer
    extraArgs:
    - --dns01-self-check-nameservers="1.1.1.1:53"
    podDnsPolicy: "None"
    podDnsConfig:
      nameservers:
      - "192.168.1.1"
