apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  destination:
    namespace: metrics
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://kubernetes-charts.storage.googleapis.com
    chart: grafana
    targetRevision: '*'
    helm:
      values: |
        envFromSecret: grafana
        env:
          GF_AUTH_BASIC_ENABLED: false
          GF_AUTH_DISABLE_LOGIN_FORM: true
          GF_SERVER_ROOT_URL: https://grafana.srueg.ch
          GF_AUTH_GENERIC_OAUTH_ENABLED: true
          GF_AUTH_GENERIC_OAUTH_NAME: Keycloak
          GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP: true
          GF_AUTH_GENERIC_OAUTH_CLIENT_ID: grafana
          GF_AUTH_GENERIC_OAUTH_AUTH_URL: https://sso.srueg.ch/auth/realms/lab/protocol/openid-connect/auth
          GF_AUTH_GENERIC_OAUTH_TOKEN_URL: https://sso.srueg.ch/auth/realms/lab/protocol/openid-connect/token
          GF_AUTH_GENERIC_OAUTH_API_URL: https://sso.srueg.ch/auth/realms/lab/protocol/openid-connect/userinfo
          GF_AUTH_GENERIC_OAUTH_API_URL_SCOPES: openid profile email
          GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: resource_access.grafana.roles
        ingress:
          enabled: true
          hosts:
          - grafana.srueg.ch
          tls:
          - hosts:
            - grafana.srueg.ch
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
            - name: Loki
              type: loki
              url: http://loki-stack.loki.cluster.local:3100
              access: proxy
              isDefault: false
        admin:
          existingSecret: grafana
        rbac:
          namespaced: true
        sidecar:
          dashboards:
            enabled: true
            label: grafana_dashboard
